### ISSUE TITLE
Looking for a JWT Crate

### ISSUE THREAD

**Issue by dbettin** [commandline/medallion#3]
Is this crate usable?  I am trying to find a JWT that I can integrate w/ Rocket.

Let me know!

**Comment by commandline** [comment]
Sorry to take so long to reply, not sure why I didn't see this when you posted.

Yes! I use this crate for several internal projects for my employer and am planning to use it as part of another project I started recently, chatelaine.

If you find any issues or require any features, please let me know by opening an issue and I will happily address.
